services:
  owner-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "123qweASD"
      ACCEPT_EULA: "Y"

  vet-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "123qweASD"
      ACCEPT_EULA: "Y"
  
  redis:
    image: redis
    ports:
      - 6379:6379

  owner:
    image: darkcat013/owner:latest
    build:
      context: ./OwnerService
      dockerfile: Dockerfile
    depends_on:
      - owner-db
    ports:
      - 32769:80
      - 32768:443

  vet:
    image: darkcat013/vet:latest
    build:
      context: ./VeterinaryService
      dockerfile: Dockerfile
    depends_on:
      - vet-db
    ports:
      - 32771:80
      - 32770:443

  gateway:
    image: darkcat013/gateway:latest
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    depends_on:
      - owner
      - vet
      - redis
    ports:
      - 8080:8080
  