apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: owner-db
spec:
  serviceName: owner-db
  replicas: 1
  selector:
    matchLabels:
      app: owner-db
  template:
    metadata:
      labels:
        app: owner-db
    spec:
      containers:
        - name: owner-db
          image: mcr.microsoft.com/mssql/server:2022-latest
          env:
            - name: SA_PASSWORD
              value: "123qweASD"
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: owner-db
spec:
  selector:
    app: owner-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vet-db
spec:
  serviceName: vet-db
  replicas: 1
  selector:
    matchLabels:
      app: vet-db
  template:
    metadata:
      labels:
        app: vet-db
    spec:
      containers:
        - name: vet-db
          image: mcr.microsoft.com/mssql/server:2022-latest
          env:
            - name: SA_PASSWORD
              value: "123qweASD"
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: vet-db
spec:
  selector:
    app: vet-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: owner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: owner
  template:
    metadata:
      labels:
        app: owner
    spec:
      containers:
        - name: owner
          image: darkcat013/owner:latest
          ports:
            - containerPort: 80
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: owner
spec:
  selector:
    app: owner
  ports:
    - name: owner-port-80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: owner-port-443
      protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vet
  template:
    metadata:
      labels:
        app: vet
    spec:
      containers:
        - name: vet
          image: darkcat013/vet:latest
          ports:
            - containerPort: 80
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: vet
spec:
  selector:
    app: vet
  ports:
    - name: owner-port-80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: owner-port-443
      protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP
  apiVersion: apps/v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: darkcat013/gateway:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
