// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: Gateway/proto/test.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestTimeoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestTimeoutRequest) Reset() {
	*x = TestTimeoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Gateway_proto_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestTimeoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTimeoutRequest) ProtoMessage() {}

func (x *TestTimeoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Gateway_proto_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTimeoutRequest.ProtoReflect.Descriptor instead.
func (*TestTimeoutRequest) Descriptor() ([]byte, []int) {
	return file_Gateway_proto_test_proto_rawDescGZIP(), []int{0}
}

type TestTimeoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestTimeoutResponse) Reset() {
	*x = TestTimeoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Gateway_proto_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestTimeoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTimeoutResponse) ProtoMessage() {}

func (x *TestTimeoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Gateway_proto_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTimeoutResponse.ProtoReflect.Descriptor instead.
func (*TestTimeoutResponse) Descriptor() ([]byte, []int) {
	return file_Gateway_proto_test_proto_rawDescGZIP(), []int{1}
}

type TestRateLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestRateLimitRequest) Reset() {
	*x = TestRateLimitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Gateway_proto_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRateLimitRequest) ProtoMessage() {}

func (x *TestRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Gateway_proto_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRateLimitRequest.ProtoReflect.Descriptor instead.
func (*TestRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_Gateway_proto_test_proto_rawDescGZIP(), []int{2}
}

type TestRateLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestRateLimitResponse) Reset() {
	*x = TestRateLimitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Gateway_proto_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRateLimitResponse) ProtoMessage() {}

func (x *TestRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Gateway_proto_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRateLimitResponse.ProtoReflect.Descriptor instead.
func (*TestRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_Gateway_proto_test_proto_rawDescGZIP(), []int{3}
}

type TestCircuitBreakerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestCircuitBreakerRequest) Reset() {
	*x = TestCircuitBreakerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Gateway_proto_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestCircuitBreakerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCircuitBreakerRequest) ProtoMessage() {}

func (x *TestCircuitBreakerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Gateway_proto_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCircuitBreakerRequest.ProtoReflect.Descriptor instead.
func (*TestCircuitBreakerRequest) Descriptor() ([]byte, []int) {
	return file_Gateway_proto_test_proto_rawDescGZIP(), []int{4}
}

type TestCircuitBreakerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestCircuitBreakerResponse) Reset() {
	*x = TestCircuitBreakerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Gateway_proto_test_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestCircuitBreakerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCircuitBreakerResponse) ProtoMessage() {}

func (x *TestCircuitBreakerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Gateway_proto_test_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCircuitBreakerResponse.ProtoReflect.Descriptor instead.
func (*TestCircuitBreakerResponse) Descriptor() ([]byte, []int) {
	return file_Gateway_proto_test_proto_rawDescGZIP(), []int{5}
}

var File_Gateway_proto_test_proto protoreflect.FileDescriptor

var file_Gateway_proto_test_proto_rawDesc = []byte{
	0x0a, 0x18, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x14, 0x0a, 0x12, 0x54, 0x65,
	0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x15, 0x0a, 0x13, 0x54, 0x65, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x54, 0x65, 0x73, 0x74, 0x52,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x17, 0x0a, 0x15, 0x54, 0x65, 0x73, 0x74, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x54, 0x65, 0x73, 0x74,
	0x43, 0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x54, 0x65, 0x73, 0x74, 0x43, 0x69, 0x72,
	0x63, 0x75, 0x69, 0x74, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0xcf, 0x01, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0b,
	0x54, 0x65, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x13, 0x2e, 0x54, 0x65,
	0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x54, 0x65, 0x73, 0x74, 0x52, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x15, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x12, 0x54, 0x65, 0x73, 0x74, 0x43, 0x69,
	0x72, 0x63, 0x75, 0x69, 0x74, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x54,
	0x65, 0x73, 0x74, 0x43, 0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x43,
	0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Gateway_proto_test_proto_rawDescOnce sync.Once
	file_Gateway_proto_test_proto_rawDescData = file_Gateway_proto_test_proto_rawDesc
)

func file_Gateway_proto_test_proto_rawDescGZIP() []byte {
	file_Gateway_proto_test_proto_rawDescOnce.Do(func() {
		file_Gateway_proto_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_Gateway_proto_test_proto_rawDescData)
	})
	return file_Gateway_proto_test_proto_rawDescData
}

var file_Gateway_proto_test_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Gateway_proto_test_proto_goTypes = []interface{}{
	(*TestTimeoutRequest)(nil),         // 0: TestTimeoutRequest
	(*TestTimeoutResponse)(nil),        // 1: TestTimeoutResponse
	(*TestRateLimitRequest)(nil),       // 2: TestRateLimitRequest
	(*TestRateLimitResponse)(nil),      // 3: TestRateLimitResponse
	(*TestCircuitBreakerRequest)(nil),  // 4: TestCircuitBreakerRequest
	(*TestCircuitBreakerResponse)(nil), // 5: TestCircuitBreakerResponse
}
var file_Gateway_proto_test_proto_depIdxs = []int32{
	0, // 0: Test.TestTimeout:input_type -> TestTimeoutRequest
	2, // 1: Test.TestRateLimit:input_type -> TestRateLimitRequest
	4, // 2: Test.TestCircuitBreaker:input_type -> TestCircuitBreakerRequest
	1, // 3: Test.TestTimeout:output_type -> TestTimeoutResponse
	3, // 4: Test.TestRateLimit:output_type -> TestRateLimitResponse
	5, // 5: Test.TestCircuitBreaker:output_type -> TestCircuitBreakerResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Gateway_proto_test_proto_init() }
func file_Gateway_proto_test_proto_init() {
	if File_Gateway_proto_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Gateway_proto_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestTimeoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Gateway_proto_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestTimeoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Gateway_proto_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestRateLimitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Gateway_proto_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestRateLimitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Gateway_proto_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestCircuitBreakerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Gateway_proto_test_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestCircuitBreakerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Gateway_proto_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Gateway_proto_test_proto_goTypes,
		DependencyIndexes: file_Gateway_proto_test_proto_depIdxs,
		MessageInfos:      file_Gateway_proto_test_proto_msgTypes,
	}.Build()
	File_Gateway_proto_test_proto = out.File
	file_Gateway_proto_test_proto_rawDesc = nil
	file_Gateway_proto_test_proto_goTypes = nil
	file_Gateway_proto_test_proto_depIdxs = nil
}
