// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: Gateway/proto/test.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Test_TestTimeout_FullMethodName        = "/Test/TestTimeout"
	Test_TestRateLimit_FullMethodName      = "/Test/TestRateLimit"
	Test_TestCircuitBreaker_FullMethodName = "/Test/TestCircuitBreaker"
)

// TestClient is the client API for Test service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestClient interface {
	TestTimeout(ctx context.Context, in *TestTimeoutRequest, opts ...grpc.CallOption) (*TestTimeoutResponse, error)
	TestRateLimit(ctx context.Context, in *TestRateLimitRequest, opts ...grpc.CallOption) (*TestRateLimitResponse, error)
	TestCircuitBreaker(ctx context.Context, in *TestCircuitBreakerRequest, opts ...grpc.CallOption) (*TestCircuitBreakerResponse, error)
}

type testClient struct {
	cc grpc.ClientConnInterface
}

func NewTestClient(cc grpc.ClientConnInterface) TestClient {
	return &testClient{cc}
}

func (c *testClient) TestTimeout(ctx context.Context, in *TestTimeoutRequest, opts ...grpc.CallOption) (*TestTimeoutResponse, error) {
	out := new(TestTimeoutResponse)
	err := c.cc.Invoke(ctx, Test_TestTimeout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) TestRateLimit(ctx context.Context, in *TestRateLimitRequest, opts ...grpc.CallOption) (*TestRateLimitResponse, error) {
	out := new(TestRateLimitResponse)
	err := c.cc.Invoke(ctx, Test_TestRateLimit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) TestCircuitBreaker(ctx context.Context, in *TestCircuitBreakerRequest, opts ...grpc.CallOption) (*TestCircuitBreakerResponse, error) {
	out := new(TestCircuitBreakerResponse)
	err := c.cc.Invoke(ctx, Test_TestCircuitBreaker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServer is the server API for Test service.
// All implementations must embed UnimplementedTestServer
// for forward compatibility
type TestServer interface {
	TestTimeout(context.Context, *TestTimeoutRequest) (*TestTimeoutResponse, error)
	TestRateLimit(context.Context, *TestRateLimitRequest) (*TestRateLimitResponse, error)
	TestCircuitBreaker(context.Context, *TestCircuitBreakerRequest) (*TestCircuitBreakerResponse, error)
	mustEmbedUnimplementedTestServer()
}

// UnimplementedTestServer must be embedded to have forward compatible implementations.
type UnimplementedTestServer struct {
}

func (UnimplementedTestServer) TestTimeout(context.Context, *TestTimeoutRequest) (*TestTimeoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestTimeout not implemented")
}
func (UnimplementedTestServer) TestRateLimit(context.Context, *TestRateLimitRequest) (*TestRateLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestRateLimit not implemented")
}
func (UnimplementedTestServer) TestCircuitBreaker(context.Context, *TestCircuitBreakerRequest) (*TestCircuitBreakerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestCircuitBreaker not implemented")
}
func (UnimplementedTestServer) mustEmbedUnimplementedTestServer() {}

// UnsafeTestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServer will
// result in compilation errors.
type UnsafeTestServer interface {
	mustEmbedUnimplementedTestServer()
}

func RegisterTestServer(s grpc.ServiceRegistrar, srv TestServer) {
	s.RegisterService(&Test_ServiceDesc, srv)
}

func _Test_TestTimeout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestTimeoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).TestTimeout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Test_TestTimeout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).TestTimeout(ctx, req.(*TestTimeoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_TestRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).TestRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Test_TestRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).TestRateLimit(ctx, req.(*TestRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_TestCircuitBreaker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestCircuitBreakerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).TestCircuitBreaker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Test_TestCircuitBreaker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).TestCircuitBreaker(ctx, req.(*TestCircuitBreakerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Test_ServiceDesc is the grpc.ServiceDesc for Test service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Test_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestTimeout",
			Handler:    _Test_TestTimeout_Handler,
		},
		{
			MethodName: "TestRateLimit",
			Handler:    _Test_TestRateLimit_Handler,
		},
		{
			MethodName: "TestCircuitBreaker",
			Handler:    _Test_TestCircuitBreaker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Gateway/proto/test.proto",
}
